In [1]:
import numpy as np

a = np.array([2,3,4])
a = a + a
a

array([4, 6, 8])

In [2]:
a.shape

(3,)

In [4]:
a = np.arange(2,10,3)
a

array([2, 5, 8])

In [7]:
a.dtype

dtype('int64')

In [9]:
a = np.arange(2.,10.,3.)
a, a.dtype

(array([ 2.,  5.,  8.]), dtype('float64'))